=== dmpfernandes/ICD-diogo-carreira-xico/xml/addQuestionRequest.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="answerBody" type="xs:string"/>
  <xs:element name="answer">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="answerBody"/>
      </xs:sequence>
      <xs:attribute type="xs:string" name="bool" use="optional"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="questionBody" type="xs:string"/>
  <xs:element name="answers">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="answer" maxOccurs="unbounded" minOccurs="0"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="addQuestionRequest">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="questionBody"/>
        <xs:element ref="answers"/>
      </xs:sequence>
      <xs:attribute type="xs:short" name="sessionNumer"/>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== dmpfernandes/ICD-diogo-carreira-xico/xml/addQuestionRequest.xml
<?xml version="1.0" encoding="UTF-8"?>
<addQuestionRequest sessionNumer="23423" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="addQuestionRequest.xsd">
	<questionBody>exemplo</questionBody>
	<answers>
        <answer bool="false">
          <answerBody>string</answerBody>
        </answer>
        <answer bool="false">
          <answerBody>string</answerBody>
        </answer>
        <answer bool="true">
          <answerBody>string</answerBody>
        </answer>
    </answers>
</addQuestionRequest>
